### ISSUE TITLE
codept broken on 4.06 due to parsetree changes

### ISSUE THREAD

**Issue by gasche** [Octachron/codept#1]
opam-builder report:

```
# File "/home/barsac/scherer/opam-builder/4.06.0+beta2+default-unsafe-string/.opam/4.06.0+beta2+default-unsafe-string/.opam-switch/build/codept.0.9.1/lib/ast_converter.ml", line 443, characters 51-55:
# Error: This expression has type object_field list
#        but an expression was expected of type ('a * 'b * core_type) list
#        Type object_field is not compatible with type 'a * 'b * core_type 
# Makefile:39: recipe for target 'lib/ast_converter.cmx' failed
```

If that can help, I recently updated camlp4 with respect to the same changes: https://github.com/ocaml/camlp4/commit/fdcdfc0b71017bb6debf0c43a943f7b90d626c5c, and maybe https://github.com/ocaml/camlp4/commit/1484d78dfb847990d1e6eb986c6b13573cd80020.

**Comment by Octachron** [comment]
Thanks a lot for the notice! The change run a bit deeper for codept since it must handle cases like https://github.com/Octachron/codept/blob/master/tests/cases/destructive_substitutions_path.ml .
Fix incoming in version .10.1 .

**Comment by Octachron** [comment]
Codept 0.10.1 with full 4.06 support is available on opam.
