### ISSUE TITLE
Nativeint not recognized

### ISSUE THREAD

**Issue by nojb** [Octachron/codept#10]
![image](https://user-images.githubusercontent.com/113560/159139666-18d6a088-1bca-44b1-ab09-11a5fe2c6251.png)

The problem may come from the fishy capitalization in 

https://github.com/Octachron/codept/blob/4a7185f84679e2cf9eb1b434a3fe9f92d945f2d3/bundled/bundle.ml#L64

**Comment by nojb** [comment]
Also: `CamlinternalOo` is missing from that same list.

**Comment by nojb** [comment]
And `Sys.Immediate64`.

**Comment by Octachron** [comment]
Thanks for the report!
This is indeed a dependency on the OCaml version that I forgot: this is a cache of the standard library signature that needs to updated on new version of the `stdlib`.

**Comment by Octachron** [comment]
This is now fixed with a test which check that the bundled stdlib maps to the real standard library across all version of OCaml 4 .

**Comment by nojb** [comment]
Thanks!
