### ISSUE TITLE
Be able to enable `debug` outputs

### ISSUE THREAD

**Issue by dinosaure** [Octachron/codept#19]
Currently, the core library has few `debug` functions which use `ifprintf`. I have a patch which allows to output these outputs if the user export `CODEPT_DEBUG=1` (and replace `ifprintf` by `fprintf`). It should be interesting to integrate that into the distribution to help me to compare my modification and what `codept` does about resolution. WDYT?

**Comment by Octachron** [comment]
That's a very good idea.
