### ISSUE TITLE
flag -dot should special case some identifiers

### ISSUE THREAD

**Issue by raphael-proust** [Octachron/codept#2]
When generating a dot file with the `-dot` option, a file name `node.ml` will cause a node of the dependency graph to be named `Node`. This is invalid in Dot

I think that `node [ name = Node ]` or something along those lines would work.

Other problematic identifiers: graph, edge, digraph, subgraph.

**Comment by Octachron** [comment]
Thanks for the report! This is fixed in master by escaping graphviz keywords as `"keyword"` when needed. This bug fix should be part of the next release by the end of the month.

**Comment by raphael-proust** [comment]
LGTM
