### ISSUE TITLE
enhancement request: extension node dependencies

### ISSUE THREAD

**Issue by mobileink** [Octachron/codept#8]
OCaml [extension nodes](https://ocaml.org/manual/extensionnodes.html) and [attributes](https://ocaml.org/manual/attributes.html) are a form of dependency. So are [extension operators and literals](https://ocaml.org/manual/extensionsyntax.html), I suppose.  I'd like to have a tool that can analyze source files and tell me what their extension points are. I'm not aware of any tool that can do this. It seems like a good fit for codept, though.

**Comment by Octachron** [comment]
Extension nodes and attributes are not really a form of dependency: they don't create an interrelated network of dependencies that must be discovered before building.

Collecting extension nodes and attributes can be done nearly directly using `compilerlibs`, I am thus not convinced by the idea of integrating this feature in codept.
